---
title: "Team Charlotte Weekly Report"
author: "Adi & David"
format: gfm
editor: visual
---

## Week 1 Report

### Team Tasks  

-   Chose a City for the Research

    -   Charlotte, North Carolina

-   Created a [spreadsheet](https://docs.google.com/spreadsheets/d/1ZFwtPYZDcX4K_ywbQWh51AtqWkiJgJTiqacHCCI4Mdc/edit#gid=0) that tracks the following:

    1.  Station Name

    2.  Address

    3.  Built Date

    4.  Coordinates

    5.  Location

    6.  Parking Availability

-   Completed GeoCoding to find coordinates of all the stations in Lynx Blue Line, Charlotte, NC

-   Created an account, project and use the Google GeoCoding API

-   Converted coordinates into spatial objects and plot them

-   Created buffers around stations and calculate daily PM2.5

-   Found sources around stations that contribute towards the PM2.5 levels

-   Created an Interactive Map with buffer zones around stations \[optional\]

### Individual Tasks

-   Complete Tidyverse DataCamp: David Guan

-   Complete Spatial Training: Adityaraj Padmanabhan
